version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: books_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - db

  php:
    image: php:8.1-fpm
    container_name: books_php
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: books_postgres
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: books_user
      POSTGRES_PASSWORD: books_password
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
